/**
 * Tile Renderer — Canvas-based tile map drawing engine.
 *
 * Rendering strategy (in priority order):
 *   1. PNG tile spritesheet  (tiles/tiles_sheet.png) — best quality, generated by generate_sprites.py
 *   2. Canvas procedural fallback — used while the sheet is loading or absent
 *
 * Water tiles always use the canvas path so wave animation still works.
 */

import type { TileType } from './sceneTiles'
import { TILE_COLORS } from './sceneTiles'
import type { SceneObject } from './sceneTiles'
import type { SpriteData } from './spriteSystem'

// ── Tile sheet integration ─────────────────────────────────────────

export const TILE_SHEET_URL = '/sprites/tiles/tiles_sheet.png'

/** Source cell size in the generated tile sheet (must match generate_sprites.py → T). */
const SHEET_TILE_SIZE = 64

/** Canonical order of tile types in the sheet — must match generate_sprites.py → TILE_ORDER. */
const TILE_ORDER: TileType[] = [
  'road_h', 'road_v', 'road_cross', 'sidewalk', 'sidewalk_edge',
  'grass', 'grass_lush', 'water', 'water_edge', 'concrete',
  'tile_plaza', 'building', 'park_path', 'fence_green', 'alley',
  'road_cross_zebra_n', 'road_cross_zebra_s', 'road_cross_zebra_w', 'road_cross_zebra_e',
  'road_stop_h', 'road_stop_v',
]
const TILE_SHEET_INDEX: Partial<Record<TileType, number>> = Object.fromEntries(
  TILE_ORDER.map((t, i) => [t, i]),
)

/** Water tiles are always drawn procedurally so animation keeps working. */
const ANIMATED_TILES = new Set<TileType>(['water', 'water_edge'])

/**
 * Tiles that always use the procedural path (never the sheet).
 * - Road tiles: need per-tile col/row noise for surface variation & patching.
 * - Building tile: needs per-tile variation so the zone doesn't look like a uniform void.
 */
const PROCEDURAL_TILES = new Set<TileType>([
  'road_h', 'road_v', 'road_cross', 'building',
  'road_cross_zebra_n', 'road_cross_zebra_s', 'road_cross_zebra_w', 'road_cross_zebra_e',
  'road_stop_h', 'road_stop_v',
])

// Seeded pseudo-random for deterministic noise per tile
function tileHash(col: number, row: number): number {
  let h = col * 374761393 + row * 668265263
  h = (h ^ (h >> 13)) * 1274126177
  return ((h ^ (h >> 16)) >>> 0) / 4294967296
}

function drawTile(
  ctx: CanvasRenderingContext2D,
  type: TileType,
  col: number,
  row: number,
  s: number,
  tick: number,
) {
  const x = col * s
  const y = row * s
  const c = TILE_COLORS[type]

  ctx.fillStyle = c.base
  ctx.fillRect(x, y, s, s)

  switch (type) {
    case 'road_h': {
      // Road surface variation: hash-based asphalt tone shift
      const surfaceOffset = ((tileHash(col * 7, row * 3) * 8) | 0) - 4
      const baseR = 68 + surfaceOffset, baseG = 68 + surfaceOffset, baseB = 72 + surfaceOffset
      ctx.fillStyle = `rgb(${baseR},${baseG},${baseB})`
      ctx.fillRect(x, y, s, s)
      // Occasional road patch (darker square)
      if (tileHash(col * 11, row * 5) > 0.82) {
        ctx.fillStyle = 'rgba(0,0,0,0.12)'
        const pw = Math.round(s * 0.35), ph = Math.round(s * 0.28)
        const px = x + Math.round(tileHash(col, row * 13) * (s - pw))
        const py2 = y + Math.round(tileHash(col * 13, row) * (s - ph))
        ctx.fillRect(px, py2, pw, ph)
      }
      // Center dashed yellow line
      ctx.fillStyle = c.line!
      const dashW = s * 0.22, gap = s * 0.14
      const cy = y + s * 0.48
      for (let dx = 0; dx < s; dx += dashW + gap) {
        ctx.fillRect(x + dx, cy, dashW, s * 0.04)
      }
      // White edge lines — slightly broken for realism
      ctx.fillStyle = c.line2!
      if (tileHash(col * 3, row) > 0.15) ctx.fillRect(x, y + 1, s, 1)
      if (tileHash(col * 5, row * 7) > 0.15) ctx.fillRect(x, y + s - 2, s, 1)
      // Asphalt grain noise
      ctx.fillStyle = c.detail!
      for (let i = 0; i < 5; i++) {
        const nx = x + tileHash(col + i * 3, row) * s
        const ny = y + tileHash(col, row + i * 3) * s
        ctx.fillRect(nx, ny, 1, 1)
      }
      break
    }

    case 'road_v': {
      const surfaceOffset = ((tileHash(col * 3, row * 7) * 8) | 0) - 4
      const baseR = 68 + surfaceOffset, baseG = 68 + surfaceOffset, baseB = 72 + surfaceOffset
      ctx.fillStyle = `rgb(${baseR},${baseG},${baseB})`
      ctx.fillRect(x, y, s, s)
      // Road patch
      if (tileHash(col * 5, row * 11) > 0.82) {
        ctx.fillStyle = 'rgba(0,0,0,0.12)'
        const pw = Math.round(s * 0.28), ph = Math.round(s * 0.35)
        const px = x + Math.round(tileHash(col * 7, row) * (s - pw))
        const py2 = y + Math.round(tileHash(col, row * 7) * (s - ph))
        ctx.fillRect(px, py2, pw, ph)
      }
      ctx.fillStyle = c.line!
      const dashH = s * 0.22, gap2 = s * 0.14
      const cx2 = x + s * 0.48
      for (let dy = 0; dy < s; dy += dashH + gap2) {
        ctx.fillRect(cx2, y + dy, s * 0.04, dashH)
      }
      ctx.fillStyle = c.line2!
      if (tileHash(col, row * 3) > 0.15) ctx.fillRect(x + 1, y, 1, s)
      if (tileHash(col * 7, row * 5) > 0.15) ctx.fillRect(x + s - 2, y, 1, s)
      ctx.fillStyle = c.detail!
      for (let i = 0; i < 5; i++) {
        const nx = x + tileHash(col + i * 3, row + 1) * s
        const ny = y + tileHash(col + 1, row + i * 3) * s
        ctx.fillRect(nx, ny, 1, 1)
      }
      break
    }

    case 'road_cross': {
      // Intersection center — clean asphalt, no markings
      const ic = ((tileHash(col * 13, row * 11) * 6) | 0) - 3
      ctx.fillStyle = `rgb(${66+ic},${66+ic},${68+ic})`
      ctx.fillRect(x, y, s, s)
      break
    }

    case 'road_cross_zebra_n':
    case 'road_cross_zebra_s':
    case 'road_cross_zebra_w':
    case 'road_cross_zebra_e': {
      const zc = ((tileHash(col * 13, row * 11) * 4) | 0) - 2
      ctx.fillStyle = `rgb(${66+zc},${66+zc},${68+zc})`
      ctx.fillRect(x, y, s, s)
      ctx.fillStyle = 'rgba(255,255,255,0.85)'
      const sw = Math.max(2, s * 0.08)
      const sg = Math.max(1, s * 0.06)
      if (type === 'road_cross_zebra_n') {
        for (let dx = s * 0.08; dx < s * 0.92; dx += sw + sg)
          ctx.fillRect(x + dx, y, sw, s * 0.2)
      } else if (type === 'road_cross_zebra_s') {
        for (let dx = s * 0.08; dx < s * 0.92; dx += sw + sg)
          ctx.fillRect(x + dx, y + s * 0.8, sw, s * 0.2)
      } else if (type === 'road_cross_zebra_w') {
        for (let dy = s * 0.08; dy < s * 0.92; dy += sw + sg)
          ctx.fillRect(x, y + dy, s * 0.2, sw)
      } else {
        for (let dy = s * 0.08; dy < s * 0.92; dy += sw + sg)
          ctx.fillRect(x + s * 0.8, y + dy, s * 0.2, sw)
      }
      break
    }

    case 'road_stop_h': {
      // road_h with a white stop line on the right edge
      const shc = ((tileHash(col, row) * 8) | 0) - 4
      ctx.fillStyle = `rgb(${68+shc},${68+shc},${70+shc})`
      ctx.fillRect(x, y, s, s)
      // Yellow center line
      ctx.fillStyle = '#FFCC00'
      ctx.fillRect(x, y + s * 0.47, s, 1)
      ctx.fillRect(x, y + s * 0.53, s, 1)
      // Stop line (white, solid, on right edge)
      ctx.fillStyle = '#FFFFFF'
      ctx.fillRect(x + s - 2, y + 2, 2, s - 4)
      break
    }

    case 'road_stop_v': {
      const svc = ((tileHash(col, row) * 8) | 0) - 4
      ctx.fillStyle = `rgb(${68+svc},${68+svc},${70+svc})`
      ctx.fillRect(x, y, s, s)
      ctx.fillStyle = '#FFCC00'
      ctx.fillRect(x + s * 0.47, y, 1, s)
      ctx.fillRect(x + s * 0.53, y, 1, s)
      ctx.fillStyle = '#FFFFFF'
      ctx.fillRect(x + 2, y + s - 2, s - 4, 2)
      break
    }

    case 'sidewalk': {
      // brick grid pattern
      ctx.fillStyle = c.line!
      const brickH = s * 0.25
      for (let dy = 0; dy < s; dy += brickH) {
        ctx.fillRect(x, y + dy, s, 1)
      }
      const brickW = s * 0.5
      for (let dy = 0; dy < s; dy += brickH * 2) {
        ctx.fillRect(x + brickW, y + dy, 1, brickH)
      }
      for (let dy = brickH; dy < s; dy += brickH * 2) {
        ctx.fillRect(x, y + dy, 1, brickH)
        ctx.fillRect(x + s - 1, y + dy, 1, brickH)
      }
      break
    }

    case 'sidewalk_edge': {
      ctx.fillStyle = c.line!
      ctx.fillRect(x, y, s, 2)
      ctx.fillStyle = c.detail!
      ctx.fillRect(x, y + 2, s, s - 2)
      break
    }

    case 'grass':
    case 'grass_lush': {
      // noise dots for grass texture
      const dotColor = c.detail!
      ctx.fillStyle = dotColor
      for (let i = 0; i < 6; i++) {
        const gx = x + tileHash(col * 7 + i, row * 3) * s
        const gy = y + tileHash(col * 3, row * 7 + i) * s
        ctx.fillRect(gx, gy, 2, 2)
      }
      // darker tufts
      ctx.fillStyle = c.line!
      for (let i = 0; i < 3; i++) {
        const gx = x + tileHash(col + i * 5, row + i * 3) * (s - 3)
        const gy = y + tileHash(col + i * 3, row + i * 5) * (s - 3)
        ctx.fillRect(gx, gy, 3, 1)
      }
      break
    }

    case 'water':
    case 'water_edge': {
      // animated wave lines
      ctx.fillStyle = c.line!
      const waveOffset = (tick * 0.8) % s
      for (let wy = 0; wy < s; wy += s * 0.3) {
        for (let wx = 0; wx < s; wx += s * 0.15) {
          const px = x + ((wx + waveOffset) % s)
          const py = y + wy + Math.sin((wx + tick * 2) * 0.3) * 2
          ctx.fillRect(px, py, s * 0.08, 1)
        }
      }
      // highlight shimmer
      if (type === 'water') {
        ctx.fillStyle = '#3A6A9A'
        const sx = x + ((tick * 1.2 + col * 7) % s)
        const sy = y + ((tick * 0.5 + row * 11) % s)
        ctx.fillRect(sx, sy, 3, 1)
      }
      break
    }

    case 'concrete': {
      ctx.fillStyle = c.detail!
      for (let i = 0; i < 4; i++) {
        const cx2 = x + tileHash(col + i, row) * s
        const cy2 = y + tileHash(col, row + i) * s
        ctx.fillRect(cx2, cy2, 2, 1)
      }
      ctx.fillStyle = c.line!
      ctx.fillRect(x, y + s - 1, s, 1)
      break
    }

    case 'tile_plaza': {
      // orthogonal tile seams
      ctx.fillStyle = c.line!
      const tileW = s * 0.5
      ctx.fillRect(x + tileW, y, 1, s)
      ctx.fillRect(x, y + tileW, s, 1)
      // subtle highlight
      ctx.fillStyle = c.detail!
      ctx.fillRect(x + 2, y + 2, tileW - 3, tileW - 3)
      break
    }

    case 'building': {
      // Building-zone concrete floor — visible medium grey (not dark void)
      const bv = ((tileHash(col * 7, row * 11) * 14) | 0)
      ctx.fillStyle = `rgb(${88 + bv},${82 + bv},${98 + bv})`
      ctx.fillRect(x, y, s, s)
      // Concrete slab seams every 2 tiles — visible grid on the floor
      ctx.fillStyle = 'rgba(0,0,0,0.30)'
      if (col % 2 === 0) ctx.fillRect(x, y, 1, s)
      if (row % 2 === 0) ctx.fillRect(x, y, s, 1)
      // Parking bay dash line every 3rd col
      if (col % 3 === 1) {
        ctx.fillStyle = 'rgba(220,215,200,0.22)'
        ctx.fillRect(x + Math.floor(s * 0.5), y + 2, 1, s - 4)
      }
      // Surface speckle
      for (let i = 0; i < 3; i++) {
        const h1 = tileHash(col * 13 + i, row * 7)
        const h2 = tileHash(col * 7, row * 13 + i)
        ctx.fillStyle = `rgba(0,0,0,${(h1 * 0.15).toFixed(2)})`
        ctx.fillRect(x + Math.floor(h1 * (s - 1)), y + Math.floor(h2 * (s - 1)), 2, 1)
      }
      break
    }

    case 'park_path': {
      // horizontal plank stripes
      ctx.fillStyle = c.line!
      const plankH = s * 0.2
      for (let dy = 0; dy < s; dy += plankH) {
        ctx.fillRect(x, y + dy, s, 1)
      }
      ctx.fillStyle = c.detail!
      ctx.fillRect(x + 1, y + 1, s - 2, s * 0.18)
      break
    }

    case 'fence_green': {
      // dense bush fill
      ctx.fillStyle = c.detail!
      ctx.fillRect(x + 1, y + 1, s - 2, s - 2)
      ctx.fillStyle = c.line!
      for (let i = 0; i < 5; i++) {
        const fx = x + tileHash(col + i * 3, row) * (s - 4) + 2
        const fy = y + tileHash(col, row + i * 3) * (s - 4) + 2
        ctx.fillRect(fx, fy, 3, 2)
      }
      break
    }

    case 'alley': {
      ctx.fillStyle = c.detail!
      ctx.fillRect(x, y, 1, s)
      ctx.fillRect(x + s - 1, y, 1, s)
      ctx.fillStyle = c.line!
      for (let i = 0; i < 2; i++) {
        const ax = x + 2 + tileHash(col + i, row) * (s - 4)
        const ay = y + tileHash(col, row + i) * s
        ctx.fillRect(ax, ay, 2, 1)
      }
      break
    }
  }
}

/**
 * Render the full tile map onto the canvas.
 *
 * @param tick   Monotonically increasing frame counter for animations.
 * @param sheet  Optional pre-loaded tile spritesheet image. When present, static
 *               tiles are sampled from the sheet; animated tiles still use the
 *               canvas path so wave motion is preserved.
 */
export function renderTileMap(
  ctx: CanvasRenderingContext2D,
  tilemap: TileType[][],
  tileSize: number,
  tick: number,
  sheet?: HTMLImageElement | null,
): void {
  const rows = tilemap.length
  const cols = tilemap[0]?.length ?? 0

  const useSheet = !!sheet && sheet.complete && sheet.naturalWidth > 0

  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const type = tilemap[r][c]

      if (useSheet && !ANIMATED_TILES.has(type) && !PROCEDURAL_TILES.has(type)) {
        const idx = TILE_SHEET_INDEX[type]
        if (idx !== undefined) {
          ctx.imageSmoothingEnabled = false
          ctx.drawImage(
            sheet!,
            idx * SHEET_TILE_SIZE, 0,    // source x, y
            SHEET_TILE_SIZE, SHEET_TILE_SIZE, // source w, h
            c * tileSize, r * tileSize,  // dest x, y
            tileSize, tileSize,          // dest w, h
          )
          continue
        }
      }

      // Fallback: canvas procedural drawing
      drawTile(ctx, type, c, r, tileSize, tick)
    }
  }
}

/** Lookup type returned by generate_sprites.py objects manifest. */
export interface ObjectManifest {
  [key: string]: { x: number; y: number; w: number; h: number }
}

import { getSpritePngKey } from './spritePngMap'

/**
 * Render scene objects (buildings, trees, lamps, etc.) on top of the tile map.
 *
 * Rendering priority per object:
 *   1. pngKey + objSheet present  → sample from PNG objects spritesheet (crisp, detailed)
 *   2. Fallback                   → SpriteData pixel-by-pixel (legacy, always works)
 *
 * Objects are bottom-anchored: tall buildings grow upward from their tile row.
 */
export function renderSceneObjects(
  ctx: CanvasRenderingContext2D,
  objects: SceneObject[],
  tileSize: number,
  objSheet?: HTMLImageElement | null,
  objManifest?: ObjectManifest | null,
): void {
  const sorted = [...objects].sort((a, b) => {
    const ay = a.zY ?? a.row
    const by = b.zY ?? b.row
    return ay - by || a.col - b.col
  })

  const canUsePng = !!objSheet && objSheet.complete && objSheet.naturalWidth > 0 && !!objManifest

  for (const obj of sorted) {
    const anchorX = obj.col * tileSize

    // ── PNG path ──────────────────────────────────────────────────
    // Resolve key: explicit pngKey on object, or registry lookup from SpriteData
    const resolvedPngKey = obj.pngKey ?? getSpritePngKey(obj.sprite)
    if (canUsePng && resolvedPngKey) {
      const entry = objManifest![resolvedPngKey]
      if (entry) {
        // Visual scale multipliers — buildings/trees must appear larger than characters
        const OBJECT_SCALE: Record<string, number> = {
          office_tower:     2.6,
          cbd_building:     2.3,
          village_building: 2.0,
          apartment_block:  2.3,
          shop_building:    1.8,
          palm_tree:        2.1,
          street_tree:      1.9,
          fountain:         1.7,
          metro_entrance:   1.7,
          bush_cluster:     1.3,
        }
        // Per-instance scale wins; otherwise fall back to key-level default
        const scaleFactor = obj.scale ?? (OBJECT_SCALE[resolvedPngKey] ?? 1.0)
        const scale  = (tileSize / 64) * scaleFactor
        const drawW  = Math.round(entry.w * scale)
        const drawH  = Math.round(entry.h * scale)
        const anchorY = (obj.row + 1) * tileSize - drawH
        ctx.imageSmoothingEnabled = true
        ctx.imageSmoothingQuality = 'high'
        ctx.drawImage(
          objSheet!,
          entry.x, entry.y, entry.w, entry.h,
          anchorX, anchorY, drawW, drawH,
        )
        continue
      }
    }

    // ── SpriteData fallback ───────────────────────────────────────
    const sprite     = obj.sprite
    const spriteCols = sprite[0]?.length ?? 0
    const spriteRows = sprite.length
    if (spriteCols === 0 || spriteRows === 0) continue

    const pixelSize = tileSize / 10
    const drawH     = spriteRows * pixelSize
    const anchorY   = (obj.row + 1) * tileSize - drawH

    for (let r = 0; r < spriteRows; r++) {
      for (let c = 0; c < spriteCols; c++) {
        const color = sprite[r][c]
        if (!color) continue
        ctx.fillStyle = color
        ctx.fillRect(
          anchorX + c * pixelSize,
          anchorY + r * pixelSize,
          Math.ceil(pixelSize),
          Math.ceil(pixelSize),
        )
      }
    }
  }
}
