/**
 * Mock 数据 - 用于 world_engine 未连接时的演示
 * 模拟 world_engine_v8.py 的 /world API 返回格式
 */

import type { WorldState, Moment } from "@/types/world";

export const MOCK_WORLD: WorldState = {
  time: {
    tick: 142,
    virtual_hour: 14,
    virtual_day: 23,
    virtual_datetime: "2025-03-23 14:30",
  },
  weather: {
    current: "多云",
    desc: "深圳的午后，云层厚重，偶有阳光穿透",
    changed_at_tick: 130,
  },
  news_feed: [
    { headline: "南山科技园某初创公司完成A轮融资，估值破亿", source: "深圳日报", tick: 140, time: "2025-03-23 13:00" },
    { headline: "华强北电子市场迎来新一波采购潮，人流量创近月新高", source: "南方都市报", tick: 138, time: "2025-03-23 12:30" },
    { headline: "深圳湾公园周末将举办马拉松，预计参与者超两万人", source: "深圳特区报", tick: 135, time: "2025-03-23 11:00" },
    { headline: "福田CBD写字楼空置率下降，商业地产回暖信号明显", source: "经济观察报", tick: 132, time: "2025-03-23 10:00" },
  ],
  hot_topics: [
    "深漂生存指南", "宝安城中村改造", "南山码农996", "华强北最新行情",
  ],
  bots: {
    "bot_1": {
      id: "bot_1", name: "陈志远", age: 28, gender: "男", origin: "湖南长沙",
      edu: "本科", home: "南山公寓", location: "南山科技园",
      hp: 82, money: 4200, energy: 65, satiety: 70, status: "alive",
      job: "前端工程师", is_sleeping: false,
      current_task: "修复线上Bug",
      current_activity: "正在疯狂敲代码，咖啡已经喝了三杯",
      emotions: { happiness: 55, sadness: 15, anger: 20, anxiety: 60, loneliness: 30 },
      desires: { lust: 20, power: 40, greed: 35, vanity: 25, security: 70 },
      skills: { tech: 78, social: 45, creative: 55, physical: 40 },
      phone_battery: 45, aging_rate: 1.0,
      reputation: { score: 12, tags: ["技术达人", "加班狂人"], deeds: [] },
      long_term_goal: "在深圳买一套属于自己的房子，不再租房",
      narrative_summary: "今天的需求改了三次，感觉要崩溃了。但想到月底的工资，还是忍了。",
      action_log: [
        { tick: 140, time: "2025-03-23 14:00", plan: "修复登录页面的Bug", result: { narrative: "花了两小时终于找到了问题所在，是一个异步竞态条件。" } },
        { tick: 138, time: "2025-03-23 13:00", plan: "去公司楼下买午饭", result: { narrative: "买了一份沙县小吃，花了18元。" } },
      ],
      generation: 1, inherited_from: null,
    },
    "bot_2": {
      id: "bot_2", name: "林晓雯", age: 26, gender: "女", origin: "广东汕头",
      edu: "硕士", home: "南山公寓", location: "福田CBD",
      hp: 90, money: 12800, energy: 80, satiety: 85, status: "alive",
      job: "金融分析师", is_sleeping: false,
      current_task: "准备季度报告",
      current_activity: "在会议室做PPT，偷偷刷手机",
      emotions: { happiness: 70, sadness: 10, anger: 15, anxiety: 45, loneliness: 25 },
      desires: { lust: 30, power: 65, greed: 55, vanity: 60, security: 50 },
      skills: { tech: 55, social: 72, creative: 48, physical: 55 },
      phone_battery: 78, aging_rate: 1.0,
      reputation: { score: 28, tags: ["职场精英", "社交达人"], deeds: [] },
      long_term_goal: "晋升为部门总监，年薪百万",
      narrative_summary: "今天的客户会议进展顺利，老板对我的报告很满意。下班后要去约会。",
      action_log: [
        { tick: 141, time: "2025-03-23 14:20", plan: "与客户开视频会议", result: { narrative: "会议进展顺利，客户对投资方案表示认可。" } },
      ],
      generation: 1, inherited_from: null,
    },
    "bot_3": {
      id: "bot_3", name: "王大柱", age: 35, gender: "男", origin: "河南郑州",
      edu: "高中", home: "宝安城中村", location: "宝安城中村",
      hp: 68, money: 820, energy: 40, satiety: 55, status: "alive",
      job: "建筑工人", is_sleeping: false,
      current_task: "找下一份工程",
      current_activity: "在村口和老乡聊天，等工头来招人",
      emotions: { happiness: 35, sadness: 40, anger: 25, anxiety: 55, loneliness: 60 },
      desires: { lust: 25, power: 15, greed: 45, vanity: 10, security: 85 },
      skills: { tech: 20, social: 50, creative: 30, physical: 85 },
      phone_battery: 30, aging_rate: 1.2,
      reputation: { score: 5, tags: ["老实人", "力气大"], deeds: [] },
      long_term_goal: "多攒点钱，回老家给儿子盖房子娶媳妇",
      narrative_summary: "上个工地结束了，还没找到新活儿。手里的钱不多了，有点慌。",
      action_log: [
        { tick: 139, time: "2025-03-23 13:30", plan: "打电话给工头问有没有活儿", result: { narrative: "工头说下周可能有个新工地开工，让我等消息。" } },
      ],
      generation: 1, inherited_from: null,
    },
    "bot_4": {
      id: "bot_4", name: "赵美琪", age: 24, gender: "女", origin: "四川成都",
      edu: "本科", home: "南山公寓", location: "深圳湾公园",
      hp: 95, money: 2100, energy: 90, satiety: 75, status: "alive",
      job: "UI设计师", is_sleeping: false,
      current_task: "找设计灵感",
      current_activity: "在海边散步，用手机拍照，寻找设计灵感",
      emotions: { happiness: 80, sadness: 5, anger: 5, anxiety: 20, loneliness: 15 },
      desires: { lust: 35, power: 25, greed: 20, vanity: 70, security: 40 },
      skills: { tech: 60, social: 65, creative: 88, physical: 70 },
      phone_battery: 62, aging_rate: 1.0,
      reputation: { score: 18, tags: ["创意达人", "生活美学"], deeds: [] },
      long_term_goal: "开一家自己的设计工作室",
      narrative_summary: "今天请了半天假来公园散心，深圳的海风真的很治愈。",
      action_log: [
        { tick: 142, time: "2025-03-23 14:25", plan: "在深圳湾拍照找灵感", result: { narrative: "拍了很多照片，发现了一个很有意思的色彩搭配。" } },
      ],
      generation: 1, inherited_from: null,
    },
    "bot_5": {
      id: "bot_5", name: "刘浩然", age: 32, gender: "男", origin: "北京",
      edu: "硕士", home: "福田CBD", location: "福田CBD",
      hp: 75, money: 85000, energy: 55, satiety: 60, status: "alive",
      job: "创业公司CEO", is_sleeping: false,
      current_task: "融资路演",
      current_activity: "在咖啡厅见投资人，谈A轮融资",
      emotions: { happiness: 50, sadness: 20, anger: 30, anxiety: 75, loneliness: 40 },
      desires: { lust: 20, power: 90, greed: 80, vanity: 75, security: 30 },
      skills: { tech: 65, social: 85, creative: 70, physical: 45 },
      phone_battery: 88, aging_rate: 1.1,
      reputation: { score: 45, tags: ["创业者", "连续创业", "融资高手"], deeds: [] },
      long_term_goal: "把公司做到上市",
      narrative_summary: "今天的投资人对我们的产品很感兴趣，但估值还有分歧。",
      action_log: [
        { tick: 141, time: "2025-03-23 14:10", plan: "向投资人展示产品Demo", result: { narrative: "投资人对产品的核心功能很感兴趣，但担心市场规模。" } },
      ],
      generation: 1, inherited_from: null,
    },
    "bot_6": {
      id: "bot_6", name: "陈小花", age: 22, gender: "女", origin: "广东梅州",
      edu: "大专", home: "宝安城中村", location: "华强北",
      hp: 88, money: 1560, energy: 75, satiety: 65, status: "alive",
      job: "电子配件销售", is_sleeping: false,
      current_task: "进货",
      current_activity: "在华强北各档口比价，寻找最便宜的配件",
      emotions: { happiness: 60, sadness: 15, anger: 20, anxiety: 35, loneliness: 45 },
      desires: { lust: 25, power: 20, greed: 50, vanity: 40, security: 65 },
      skills: { tech: 45, social: 70, creative: 35, physical: 60 },
      phone_battery: 55, aging_rate: 1.0,
      reputation: { score: 8, tags: ["砍价高手", "勤快"], deeds: [] },
      long_term_goal: "存够钱开一家自己的网店",
      narrative_summary: "今天进了一批新款手机壳，利润不错。华强北的行情变化真快。",
      action_log: [
        { tick: 140, time: "2025-03-23 14:00", plan: "去B3区进货", result: { narrative: "以批发价买入了200个手机壳，利润空间约30%。" } },
      ],
      generation: 1, inherited_from: null,
    },
    "bot_7": {
      id: "bot_7", name: "张国强", age: 45, gender: "男", origin: "湖北武汉",
      edu: "本科", home: "宝安城中村", location: "东门老街",
      hp: 70, money: 6800, energy: 50, satiety: 80, status: "alive",
      job: "餐饮老板", is_sleeping: false,
      current_task: "备货",
      current_activity: "在市场采购新鲜食材，准备晚市",
      emotions: { happiness: 55, sadness: 20, anger: 35, anxiety: 40, loneliness: 50 },
      desires: { lust: 15, power: 30, greed: 55, vanity: 20, security: 75 },
      skills: { tech: 25, social: 60, creative: 55, physical: 70 },
      phone_battery: 40, aging_rate: 1.1,
      reputation: { score: 22, tags: ["厨艺精湛", "老实商人"], deeds: [] },
      long_term_goal: "把餐馆开成连锁，让老婆孩子过上好日子",
      narrative_summary: "今天猪肉涨价了，成本又高了。但客人还是很多，撑得住。",
      action_log: [
        { tick: 138, time: "2025-03-23 13:00", plan: "去菜市场采购", result: { narrative: "买了新鲜猪肉和蔬菜，花了320元。猪肉比上周贵了5元/斤。" } },
      ],
      generation: 1, inherited_from: null,
    },
    "bot_8": {
      id: "bot_8", name: "李梦婷", age: 29, gender: "女", origin: "江苏南京",
      edu: "本科", home: "南山公寓", location: "南山科技园",
      hp: 85, money: 5600, energy: 70, satiety: 72, status: "alive",
      job: "产品经理", is_sleeping: false,
      current_task: "用户调研",
      current_activity: "在公司茶水间和同事讨论新功能方向",
      emotions: { happiness: 65, sadness: 10, anger: 25, anxiety: 50, loneliness: 20 },
      desires: { lust: 30, power: 55, greed: 40, vanity: 50, security: 55 },
      skills: { tech: 58, social: 78, creative: 72, physical: 50 },
      phone_battery: 70, aging_rate: 1.0,
      reputation: { score: 20, tags: ["产品思维", "用户导向"], deeds: [] },
      long_term_goal: "做出一款真正改变用户生活的产品",
      narrative_summary: "今天的用户访谈很有收获，发现了一个之前没注意到的痛点。",
      action_log: [
        { tick: 141, time: "2025-03-23 14:15", plan: "整理用户访谈笔记", result: { narrative: "发现用户最痛苦的点是操作流程太复杂，需要简化。" } },
      ],
      generation: 1, inherited_from: null,
    },
  },
  locations: {
    "宝安城中村": {
      desc: "密集的握手楼，廉价的出租屋，外来务工人员的聚居地",
      type: "residential",
      bots: ["bot_3"],
      npcs: [{ name: "房东老李", role: "收租" }, { name: "工头老王", role: "招工" }],
      jobs: [{ title: "建筑工人", pay: 80 }, { title: "快递员", pay: 60 }],
      public_memory: [
        { event: "王大柱在村口等工头招工", actor: "bot_3", tick: 139, impact: "low" },
        { event: "昨晚有人在楼道里大声打电话，吵到了很多人", actor: "unknown", tick: 135, impact: "low" },
      ],
      vibe: "拥挤嘈杂",
    },
    "南山科技园": {
      desc: "深圳科技创新的心脏，汇聚了无数互联网大厂和初创公司",
      type: "business",
      bots: ["bot_1", "bot_8"],
      npcs: [{ name: "前台小姐姐", role: "接待" }, { name: "保安大叔", role: "安保" }],
      jobs: [{ title: "程序员", pay: 200 }, { title: "产品经理", pay: 180 }, { title: "运营", pay: 120 }],
      public_memory: [
        { event: "陈志远修复了一个困扰团队三天的Bug，获得同事称赞", actor: "bot_1", tick: 140, impact: "medium" },
        { event: "李梦婷组织了一次用户访谈，收获颇丰", actor: "bot_8", tick: 141, impact: "medium" },
      ],
      vibe: "高压充实",
    },
    "福田CBD": {
      desc: "深圳的金融中心，高楼林立，西装革履的人们行色匆匆",
      type: "business",
      bots: ["bot_2", "bot_5"],
      npcs: [{ name: "投资人王总", role: "投资" }, { name: "咖啡师", role: "服务" }],
      jobs: [{ title: "金融分析师", pay: 250 }, { title: "律师助理", pay: 150 }],
      public_memory: [
        { event: "林晓雯的季度报告获得老板高度评价", actor: "bot_2", tick: 141, impact: "high" },
        { event: "刘浩然正在与投资人谈判A轮融资", actor: "bot_5", tick: 141, impact: "high" },
      ],
      vibe: "商业气息浓厚",
    },
    "华强北": {
      desc: "全球最大的电子元器件集散地，每天流转着数以亿计的货物",
      type: "commercial",
      bots: ["bot_6"],
      npcs: [{ name: "档口老板", role: "销售" }, { name: "黄牛阿强", role: "倒卖" }],
      jobs: [{ title: "销售员", pay: 100 }, { title: "配件采购", pay: 90 }],
      public_memory: [
        { event: "陈小花以极低价格拿到了一批新款手机壳", actor: "bot_6", tick: 140, impact: "medium" },
      ],
      vibe: "热闹繁忙",
    },
    "东门老街": {
      desc: "深圳最古老的商业街区，传统与现代在这里交汇",
      type: "commercial",
      bots: ["bot_7"],
      npcs: [{ name: "算命先生", role: "算命" }, { name: "老街坊", role: "闲聊" }],
      jobs: [{ title: "餐饮服务员", pay: 70 }, { title: "小贩", pay: 50 }],
      public_memory: [
        { event: "张国强的餐馆今天生意不错，翻台三次", actor: "bot_7", tick: 138, impact: "medium" },
      ],
      vibe: "烟火气十足",
    },
    "南山公寓": {
      desc: "南山区的普通住宅区，住着大量在科技公司工作的年轻人",
      type: "residential",
      bots: [],
      npcs: [{ name: "物业大爷", role: "管理" }],
      jobs: [],
      public_memory: [
        { event: "楼道里有人贴了招租广告", actor: "unknown", tick: 130, impact: "low" },
      ],
      vibe: "安静宜居",
    },
    "深圳湾公园": {
      desc: "深圳最美的滨海公园，可以看到香港的轮廓",
      type: "leisure",
      bots: ["bot_4"],
      npcs: [{ name: "晨跑大妈", role: "锻炼" }, { name: "钓鱼老伯", role: "垂钓" }],
      jobs: [],
      public_memory: [
        { event: "赵美琪在海边拍到了一组很美的照片", actor: "bot_4", tick: 142, impact: "low" },
      ],
      vibe: "清新舒适",
    },
  },
  events: [
    { tick: 140, time: "2025-03-23 14:00", event: "经济波动", desc: "深圳房价再次上涨，打工人的买房梦更遥远了" },
    { tick: 135, time: "2025-03-23 11:00", event: "天气变化", desc: "台风外围云系影响，深圳今日多云，体感闷热" },
  ],
  world_narrative: "这是深圳的第23天。10个来自五湖四海的人，在这座城市里各自挣扎、奋斗、寻找属于自己的位置。",
  world_modifications: [
    { name: "陈小花的手机壳摊位", description: "在华强北B3区开了一个小摊位", type: "business", creator: "bot_6", creator_name: "陈小花", location: "华强北", tick: 120, time: "2025-03-22 10:00" },
  ],
  generation_count: 1,
  graveyard: [],
};

export const MOCK_MOMENTS: Moment[] = [
  {
    id: "m1", bot_id: "bot_4", bot_name: "赵美琪",
    content: "深圳湾的下午，海风很温柔 🌊 今天请假出来散心，感觉整个人都治愈了。设计灵感也来了！",
    tick: 142, time: "2025-03-23 14:25",
    likes: ["bot_2", "bot_8", "bot_1"],
    comments: [
      { bot_id: "bot_2", bot_name: "林晓雯", content: "好羡慕！我还在开会😭", tick: 142 },
      { bot_id: "bot_8", bot_name: "李梦婷", content: "下次带我一起！", tick: 142 },
    ],
  },
  {
    id: "m2", bot_id: "bot_1", bot_name: "陈志远",
    content: "终于找到那个Bug了！！！异步竞态条件，找了两个小时。程序员的快乐就是这么朴实无华。",
    tick: 140, time: "2025-03-23 14:00",
    likes: ["bot_8"],
    comments: [
      { bot_id: "bot_8", bot_name: "李梦婷", content: "哈哈哈 辛苦了！", tick: 140 },
    ],
  },
  {
    id: "m3", bot_id: "bot_5", bot_name: "刘浩然",
    content: "今天见了三个投资人，每个人都说我们的方向很好，但都没给钱。融资真的太难了。",
    tick: 139, time: "2025-03-23 13:30",
    likes: ["bot_2"],
    comments: [
      { bot_id: "bot_2", bot_name: "林晓雯", content: "加油！你们的产品我用过，真的很好用", tick: 139 },
    ],
  },
  {
    id: "m4", bot_id: "bot_3", bot_name: "王大柱",
    content: "在村口等工头，等了一上午了。手里的钱快撑不住了，有点慌。深圳真的不好混啊。",
    tick: 138, time: "2025-03-23 13:00",
    likes: [],
    comments: [],
  },
];
